insert into depara_conta_financeira values('SALDO INICIAL')
insert into depara_conta_financeira values('TRANSFERÊNCIA ENTRE CONTAS')
insert into depara_conta_financeira values('RECEITAS OPERACIONAIS')
insert into depara_conta_financeira values('RECEITAS NÃO OPERACIONAIS')
insert into depara_conta_financeira values('DEDUCOES DE RECEITA')
insert into depara_conta_financeira values('IMPOSTOS E CONTRIBUICOES')
insert into depara_conta_financeira values('DESPESAS COM PESSOAL')
insert into depara_conta_financeira values('OUTRAS DESPESAS COM PESSOAL')
insert into depara_conta_financeira values('SERVICOS MEDICOS E ASSISTENCIAIS')
insert into depara_conta_financeira values('CONSUMO DE MATERIAL HOSPITALAR E MEDICAMENTOS')
insert into depara_conta_financeira values('CONSUMO DE MATERIAIS GERAIS')
insert into depara_conta_financeira values('SERVIÇOS TÉCNICOS E OPERACIONAIS')
insert into depara_conta_financeira values('SERVIÇOS DE APOIO E LOGÍSTICA')
insert into depara_conta_financeira values('MANUTENCAO E ASSISTENCIA TECNICA')
insert into depara_conta_financeira values('DESPESAS TECNOLOGIA DA INFORMACAO')
insert into depara_conta_financeira values('DESPESAS DE SERVICOS NÃO OPERACIONAIS')
insert into depara_conta_financeira values('OUTRAS DESPESAS ADMINISTRATIVAS')
insert into depara_conta_financeira values('UTILIDADES')
insert into depara_conta_financeira values('TAXAS ADMINISTRATIVAS E DE SERVIÇOS DIVERSOS')
insert into depara_conta_financeira values('DESPESAS LEGAIS E JUDICIAIS')
insert into depara_conta_financeira values('IMPOSTOS E TAXAS')
insert into depara_conta_financeira values('SEGUROS')
insert into depara_conta_financeira values('DESPESAS FINANCEIRAS/BANCARIAS')
