Insert into depara_centro_custos values ('Pronto Atendimento')
Insert into depara_centro_custos values ('Centro Cirurgico')
Insert into depara_centro_custos values ('Ambulatorio')
Insert into depara_centro_custos values ('UI')
Insert into depara_centro_custos values ('UTI')
Insert into depara_centro_custos values ('Geral')
Insert into depara_centro_custos values ('Tecnologia Informacao')
Insert into depara_centro_custos values ('Farmacia')
